### ISSUE TITLE
رسالة شكر

### ISSUE THREAD

**Issue by Asux30** [zecopro/wpa-passwords#1]
شكرا لك على هذه اللستات.
وعندي لك بسؤال لو سمحت:
هل يمكنك أن تعمل ليست بدون تكرار الحروف أكثر من ثلاث مرات؟!

**Comment by zecopro** [comment]
مممكن تعمل هذاا الشي وممكن تعملة بعد انشاء اللستات عن طريق فلاتر خاصة

**Comment by Asux30** [comment]
ممكن أن تريني الطريقة أو فيديو يشرحها؟
