### ISSUE TITLE
عندي فكره لتجميع باسوردات وايفاي رائعه جدا 

### ISSUE THREAD

**Issue by minanagehsalalma** [zecopro/wpa-passwords#2]
لدي فكره لتجميع باسوردات وايفاي قد تصل نسبه نجاح اللسته شبكتين من اصل اربع شبكات . اخبرني انك موافق وسأخبرك بالطريقه . ارجو ان تشاركني ايها 😊😊😊😊😊😊😊😊

**Comment by zecopro** [comment]
اطرح فكرتك صديقي ولو جيدة وفعالة نوعمل عليها شرح في القناة

**Comment by minanagehsalalma** [comment]
بص في فكره معرفتش اعملها  اذا وهي اني اخد اللسته من تطبيق وايفاي ماب علي الاندرويد وبعد مخدتها لقيتها ملغبطه وعمله زي قاعده البيانات وكان في طريقه انقلا بيها الباسوردات بس  ببرنامج vim edatior 
بس معرفتش اعملها والطرييقه التانيه محتاجه وقت شويه لانها بعتمد علي برنامج 
router scan 
وانا جهزت الايبهات وكان مفروض احتها وانقل الباسوردات بتاعت  وايفاي الرواتر بعد ما الاسكان يخلص بس الايبهات كانت كتيرا عليا ...
وادي الايبهات واحدث اصدار من 
router scan 
[RSTest.zip](https://github.com/zecopro/wpa-passwords/files/1729832/RSTest.zip)
[ips.txt](https://github.com/zecopro/wpa-passwords/files/1729834/ips.txt)

@zecopro

**Comment by minanagehsalalma** [comment]
@zecopro   ها اخي عجبتك الفكره ؟

**Comment by zecopro** [comment]
فكرتك رائعة جدا بس مشكلة صديقي هو مو كل الرواترات فيها ريموت خارجي او حتى لو كان مو كلهة تكون مفعلة بالاضافة الى ذلك لا يوجد رينج خاص لمجموعة االرواترات القريبة عندك هذا راح يسبب مشكلة انو انت راح تستخرج ايبيات لرواترات بعيدة جدا

**Comment by minanagehsalalma** [comment]
@zecopro  من وين انت .. دي ايبهات اكثر شركه النت استخداما عندي في بلدي .. فا مش هتفرق الرواتر بعيده ولا لا انا كل اعتمادي علي تشابه الباسوردات عشان التخمين مش اكتر !!! ..
ويه رأيك في vim edatior؟؟ 
ادي رابط سألت فيه عنوا 
[الرابط](https://www.reddit.com/r/linuxquestions/comments/71se7n/help_with_vim_editor/)

**Comment by minanagehsalalma** [comment]
اخي لقيت طريقه القيام بي الاوله @zecopro
